PLEASE DO ,1 <- #5
PLEASE DO ,1 SUB #1 <- #5
PLEASE DO ,1 SUB #2 <- #1
PLEASE DO ,1 SUB #3 <- #4
PLEASE DO ,1 SUB #4 <- #2
PLEASE DO ,1 SUB #5 <- #3
PLEASE WRITE OUT ,1 SUB #1
PLEASE WRITE OUT ,1 SUB #2
PLEASE WRITE OUT ,1 SUB #3
PLEASE WRITE OUT ,1 SUB #4
PLEASE WRITE OUT ,1 SUB #5
PLEASE GIVE UP